# Generated by Django 4.2.7 on 2024-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date",
            field=models.CharField(max_length=100, null=True, verbose_name="date"),
        ),
        migrations.AddField(
            model_name="client",
            name="heading",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="heading text"
            ),
        ),
    ]
