# Generated by Django 4.2.7 on 2024-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_client_date_client_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="link",
            field=models.TextField(null=True, verbose_name="link"),
        ),
    ]
