# Generated by Django 4.2.7 on 2024-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_service_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentwork",
            name="category",
            field=models.TextField(null=True, verbose_name="category"),
        ),
        migrations.AddField(
            model_name="recentwork",
            name="link",
            field=models.TextField(null=True, verbose_name="link"),
        ),
    ]
