# Generated by Django 4.2.7 on 2024-06-25 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_remove_client_image_client_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="date",
        ),
        migrations.RemoveField(
            model_name="client",
            name="description",
        ),
        migrations.RemoveField(
            model_name="client",
            name="heading",
        ),
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
    ]
